### ISSUE TITLE
problem installation 

### ISSUE THREAD

**Issue by midjarmaksor** [takshal/freq#5]
package https:/github.com/takshal/freq: https:/github.com/takshal/freq: invalid import path: malformed import path "https:/github.com/takshal/freq": invalid char ':'

**Comment by DhiralGit** [comment]
> 

Remove HTTPS from path

**Comment by rohit0x5** [comment]
> > 
> 
> Remove HTTPS:/ from path

same error on this go get -u http://github.com/takshal/freq

**Comment by rohit0x5** [comment]
> > 
> 
> Remove HTTPS:/ from path

go get -u github.com/takshal/freq this work great

**Comment by luckythandel** [comment]
```bash
sudo go install github.com/takshal/freq@latest
```
Then the binary should be in `/root/go/bin/`

**Comment by takshal** [comment]
you can download a binary and run with go run main.go

**Comment by Dadichi008** [comment]
Getting error tried each possible way. Pls. help me 
![freq_er](https://user-images.githubusercontent.com/98478809/159223882-efa9753e-52b4-41c4-9ca7-fa1c16bb35ca.png)
