### ISSUE TITLE
Code breaking Issue

### ISSUE THREAD

**Issue by tiklup11** [takshal/freq#6]
https://twitter.com/ofjaaah/status/1504932805431767046?s=28

I was implementing the method discussed in the above tweet.
`echo http://testphp.vulnweb.com | waybackurls | gf xss | uro | qsreplace '"><img src=x onerror=alert(1);>' | freq`

This command only outputs the below lines and breaks [perhaps]. Can you test?
```
frequester tool By tojojo !!
\__(-_-)__/

**Comment by Amal03-bit** [comment]
am also facing the same problem

**Comment by rahul199300** [comment]
Hey dear i am also facing this is when using this command line- 

echo http://testphp.vulnweb.com | waybackurls | gf xss | uro | qsreplace '"><img src=x onerror=alert(1);>' | freq 

error massage-

frequester tool By tojojo !!
\__(-_-)__/
gf: command not found
Command 'uro' not found, did you mean:
  command 'ro' from deb golang-redoctober
  command 'ur' from deb libur-perl
  command 'udo' from deb udo
  command 'bro' from deb bro
Try: apt install <deb name>
qsreplace: command not found
waybackurls: command not found


how i can fix it please help

**Comment by Amal03-bit** [comment]
you need to install all the tools 

pip3 install uro

check all the links

https://github.com/tomnomnom/waybackurls
https://github.com/tomnomnom/gf
https://github.com/tomnomnom/qsreplace
